# https://docs.microsoft.com/azure/devops/pipelines/languages/python

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    # Python27:
    #   python.version: '2.7'
    Python35:
      python.version: '3.5'
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    pip install pipenv
    pipenv install
  displayName: 'Install dependencies'

- script: |
    pipenv run azdev setup -r $PWD
  displayName: 'Install azdev'

- script: |
    pipenv run azdev extension list
    # pipenv run azdev extension add azure-vmware-virtustream-cli-extension
    # I do not understand why azdev is using the directory name.
    nm=${PWD##*/}
    pipenv run azdev extension add $nm
  displayName: 'Add extension'

- script: |
    pipenv run azdev test VmwareScenarioTest
  displayName: 'Run tests'