# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

try:
    from .global_reach_connection_request_py3 import GlobalReachConnectionRequest
    from .delete_global_reach_connection_request_py3 import DeleteGlobalReachConnectionRequest
    from .global_reach_connection_py3 import GlobalReachConnection
    from .express_route_authorization_py3 import ExpressRouteAuthorization
    from .circuit_py3 import Circuit
    from .cluster_request_py3 import ClusterRequest
    from .endpoints_py3 import Endpoints
    from .add_identity_source_request_py3 import AddIdentitySourceRequest
    from .delete_identity_source_request_py3 import DeleteIdentitySourceRequest
    from .identity_source_py3 import IdentitySource
    from .cluster_py3 import Cluster
    from .private_cloud_py3 import PrivateCloud
    from .azure_private_cloud_response_py3 import AzurePrivateCloudResponse
    from .private_cloud_list_py3 import PrivateCloudList
    from .azure_private_cloud_request_py3 import AzurePrivateCloudRequest
    from .azure_cluster_request_py3 import AzureClusterRequest
    from .azure_cluster_response_py3 import AzureClusterResponse
    from .azure_operation_status_py3 import AzureOperationStatus
    from .get_admin_credentials_response_py3 import GetAdminCredentialsResponse
    from .move_resource_request_py3 import MoveResourceRequest
except (SyntaxError, ImportError):
    from .global_reach_connection_request import GlobalReachConnectionRequest
    from .delete_global_reach_connection_request import DeleteGlobalReachConnectionRequest
    from .global_reach_connection import GlobalReachConnection
    from .express_route_authorization import ExpressRouteAuthorization
    from .circuit import Circuit
    from .cluster_request import ClusterRequest
    from .endpoints import Endpoints
    from .add_identity_source_request import AddIdentitySourceRequest
    from .delete_identity_source_request import DeleteIdentitySourceRequest
    from .identity_source import IdentitySource
    from .cluster import Cluster
    from .private_cloud import PrivateCloud
    from .azure_private_cloud_response import AzurePrivateCloudResponse
    from .private_cloud_list import PrivateCloudList
    from .azure_private_cloud_request import AzurePrivateCloudRequest
    from .azure_cluster_request import AzureClusterRequest
    from .azure_cluster_response import AzureClusterResponse
    from .azure_operation_status import AzureOperationStatus
    from .get_admin_credentials_response import GetAdminCredentialsResponse
    from .move_resource_request import MoveResourceRequest

__all__ = [
    'GlobalReachConnectionRequest',
    'DeleteGlobalReachConnectionRequest',
    'GlobalReachConnection',
    'ExpressRouteAuthorization',
    'Circuit',
    'ClusterRequest',
    'Endpoints',
    'AddIdentitySourceRequest',
    'DeleteIdentitySourceRequest',
    'IdentitySource',
    'Cluster',
    'PrivateCloud',
    'AzurePrivateCloudResponse',
    'PrivateCloudList',
    'AzurePrivateCloudRequest',
    'AzureClusterRequest',
    'AzureClusterResponse',
    'AzureOperationStatus',
    'GetAdminCredentialsResponse',
    'MoveResourceRequest',
]
