# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AzureOperationStatus(Model):
    """AzureOperationStatus.

    :param end_time:
    :type end_time: str
    :param id:
    :type id: str
    :param percent_complete:
    :type percent_complete: float
    :param properties:
    :type properties: ~vendored_sdks.models.PrivateCloud
    :param start_time:
    :type start_time: str
    :param status: Possible values include: 'Succeeded', 'Failed', 'Cancelled'
    :type status: str or ~vendored_sdks.models.enum
    """

    _attribute_map = {
        'end_time': {'key': 'endTime', 'type': 'str'},
        'id': {'key': 'id', 'type': 'str'},
        'percent_complete': {'key': 'percentComplete', 'type': 'float'},
        'properties': {'key': 'properties', 'type': 'PrivateCloud'},
        'start_time': {'key': 'startTime', 'type': 'str'},
        'status': {'key': 'status', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(AzureOperationStatus, self).__init__(**kwargs)
        self.end_time = kwargs.get('end_time', None)
        self.id = kwargs.get('id', None)
        self.percent_complete = kwargs.get('percent_complete', None)
        self.properties = kwargs.get('properties', None)
        self.start_time = kwargs.get('start_time', None)
        self.status = kwargs.get('status', None)
