# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AzurePrivateCloudRequest(Model):
    """AzurePrivateCloudRequest.

    :param location:
    :type location: str
    :param properties:
    :type properties: ~vendored_sdks.models.PrivateCloud
    :param tags:
    :type tags: object
    """

    _attribute_map = {
        'location': {'key': 'location', 'type': 'str'},
        'properties': {'key': 'properties', 'type': 'PrivateCloud'},
        'tags': {'key': 'tags', 'type': 'object'},
    }

    def __init__(self, **kwargs):
        super(AzurePrivateCloudRequest, self).__init__(**kwargs)
        self.location = kwargs.get('location', None)
        self.properties = kwargs.get('properties', None)
        self.tags = kwargs.get('tags', None)
