# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AzureClusterRequest(Model):
    """AzureClusterRequest.

    :param location:
    :type location: str
    :param properties:
    :type properties: ~vendored_sdks.models.ClusterRequest
    """

    _attribute_map = {
        'location': {'key': 'location', 'type': 'str'},
        'properties': {'key': 'properties', 'type': 'ClusterRequest'},
    }

    def __init__(self, **kwargs):
        super(AzureClusterRequest, self).__init__(**kwargs)
        self.location = kwargs.get('location', None)
        self.properties = kwargs.get('properties', None)
