# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AzureOperationStatus(Model):
    """AzureOperationStatus.

    :param end_time:
    :type end_time: str
    :param id:
    :type id: str
    :param percent_complete:
    :type percent_complete: float
    :param properties:
    :type properties: ~vendored_sdks.models.PrivateCloud
    :param start_time:
    :type start_time: str
    :param status: Possible values include: 'Succeeded', 'Failed', 'Cancelled'
    :type status: str or ~vendored_sdks.models.enum
    """

    _attribute_map = {
        'end_time': {'key': 'endTime', 'type': 'str'},
        'id': {'key': 'id', 'type': 'str'},
        'percent_complete': {'key': 'percentComplete', 'type': 'float'},
        'properties': {'key': 'properties', 'type': 'PrivateCloud'},
        'start_time': {'key': 'startTime', 'type': 'str'},
        'status': {'key': 'status', 'type': 'str'},
    }

    def __init__(self, *, end_time: str=None, id: str=None, percent_complete: float=None, properties=None, start_time: str=None, status=None, **kwargs) -> None:
        super(AzureOperationStatus, self).__init__(**kwargs)
        self.end_time = end_time
        self.id = id
        self.percent_complete = percent_complete
        self.properties = properties
        self.start_time = start_time
        self.status = status
