# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Cluster(Model):
    """Cluster.

    :param provisioning_state: Possible values include: 'Succeeded', 'Failed',
     'Cancelled', 'Updating'
    :type provisioning_state: str or ~vendored_sdks.models.enum
    :param cluster_size:
    :type cluster_size: int
    :param hosts:
    :type hosts: list[str]
    """

    _attribute_map = {
        'provisioning_state': {'key': 'provisioningState', 'type': 'str'},
        'cluster_size': {'key': 'clusterSize', 'type': 'int'},
        'hosts': {'key': 'hosts', 'type': '[str]'},
    }

    def __init__(self, *, provisioning_state=None, cluster_size: int=None, hosts=None, **kwargs) -> None:
        super(Cluster, self).__init__(**kwargs)
        self.provisioning_state = provisioning_state
        self.cluster_size = cluster_size
        self.hosts = hosts
