# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ClusterRequest(Model):
    """ClusterRequest.

    :param cluster_size: number of hosts in PrivateCloud cluster
    :type cluster_size: int
    """

    _attribute_map = {
        'cluster_size': {'key': 'clusterSize', 'type': 'int'},
    }

    def __init__(self, **kwargs):
        super(ClusterRequest, self).__init__(**kwargs)
        self.cluster_size = kwargs.get('cluster_size', None)
