# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .default_cluster_properties import DefaultClusterProperties


class ClusterProperties(DefaultClusterProperties):
    """The properties of a cluster.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar cluster_id: The identity
    :vartype cluster_id: int
    :param cluster_size: The cluster size
    :type cluster_size: int
    :ivar hosts: The hosts
    :vartype hosts: list[str]
    :ivar provisioning_state: The state of the cluster provisioning. Possible
     values include: 'Succeeded', 'Failed', 'Cancelled', 'Updating'
    :vartype provisioning_state: str or
     ~vendored_sdks.models.ClusterProvisioningState
    """

    _validation = {
        'cluster_id': {'readonly': True},
        'hosts': {'readonly': True},
        'provisioning_state': {'readonly': True},
    }

    _attribute_map = {
        'cluster_id': {'key': 'clusterId', 'type': 'int'},
        'cluster_size': {'key': 'clusterSize', 'type': 'int'},
        'hosts': {'key': 'hosts', 'type': '[str]'},
        'provisioning_state': {'key': 'provisioningState', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(ClusterProperties, self).__init__(**kwargs)
        self.provisioning_state = None
