# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .default_cluster_properties_py3 import DefaultClusterProperties


class ClusterProperties(DefaultClusterProperties):
    """ClusterProperties.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar cluster_id:
    :vartype cluster_id: int
    :param cluster_size:
    :type cluster_size: int
    :ivar hosts:
    :vartype hosts: list[str]
    :ivar provisioning_state: Possible values include: 'Succeeded', 'Failed',
     'Cancelled', 'Updating'
    :vartype provisioning_state: str or
     ~vendored_sdks.models.ClusterProvisioningState
    """

    _validation = {
        'cluster_id': {'readonly': True},
        'hosts': {'readonly': True},
        'provisioning_state': {'readonly': True},
    }

    _attribute_map = {
        'cluster_id': {'key': 'clusterId', 'type': 'int'},
        'cluster_size': {'key': 'clusterSize', 'type': 'int'},
        'hosts': {'key': 'hosts', 'type': '[str]'},
        'provisioning_state': {'key': 'provisioningState', 'type': 'str'},
    }

    def __init__(self, *, cluster_size: int=None, **kwargs) -> None:
        super(ClusterProperties, self).__init__(cluster_size=cluster_size, **kwargs)
        self.provisioning_state = None
