# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DeleteGlobalReachConnectionRequest(Model):
    """DeleteGlobalReachConnectionRequest.

    :param id:
    :type id: str
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(DeleteGlobalReachConnectionRequest, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
