# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ExpressRouteAuthorization(Model):
    """Authorization for an ExpressRoute.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param name: The name of the ExpressRoute
    :type name: str
    :ivar id: The ID of the ExpressRoute
    :vartype id: str
    :ivar key: The key of the ExpressRoute
    :vartype key: str
    """

    _validation = {
        'id': {'readonly': True},
        'key': {'readonly': True},
    }

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'id': {'key': 'id', 'type': 'str'},
        'key': {'key': 'key', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(ExpressRouteAuthorization, self).__init__(**kwargs)
        self.name = kwargs.get('name', None)
        self.id = None
        self.key = None
