# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class GetAdminCredentialsResponse(Model):
    """GetAdminCredentialsResponse.

    :param user:
    :type user: str
    :param password:
    :type password: str
    """

    _attribute_map = {
        'user': {'key': 'user', 'type': 'str'},
        'password': {'key': 'password', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(GetAdminCredentialsResponse, self).__init__(**kwargs)
        self.user = kwargs.get('user', None)
        self.password = kwargs.get('password', None)
