# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class GlobalReachConnection(Model):
    """GlobalReachConnection.

    :param id:
    :type id: str
    :param primary_subnet:
    :type primary_subnet: str
    :param secondary_subnet:
    :type secondary_subnet: str
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'primary_subnet': {'key': 'primarySubnet', 'type': 'str'},
        'secondary_subnet': {'key': 'secondarySubnet', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(GlobalReachConnection, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.primary_subnet = kwargs.get('primary_subnet', None)
        self.secondary_subnet = kwargs.get('secondary_subnet', None)
