# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PrivateCloudList(Model):
    """PrivateCloudList.

    :param value:
    :type value: list[~vendored_sdks.models.AzurePrivateCloudResponse]
    """

    _attribute_map = {
        'value': {'key': 'value', 'type': '[AzurePrivateCloudResponse]'},
    }

    def __init__(self, **kwargs):
        super(PrivateCloudList, self).__init__(**kwargs)
        self.value = kwargs.get('value', None)
