# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from enum import Enum


class QuotaEnabled(str, Enum):

    enabled = "Enabled"
    disabled = "Disabled"


class SslEnum(str, Enum):

    enabled = "Enabled"
    disabled = "Disabled"


class PrivateCloudProvisioningState(str, Enum):

    succeeded = "Succeeded"
    failed = "Failed"
    cancelled = "Cancelled"
    pending = "Pending"
    building = "Building"
    updating = "Updating"


class InternetEnum(str, Enum):

    enabled = "Enabled"
    disabled = "Disabled"


class ClusterProvisioningState(str, Enum):

    succeeded = "Succeeded"
    failed = "Failed"
    cancelled = "Cancelled"
    updating = "Updating"
