# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Vpc(Model):
    """Vpc.

    :param tenant_mgmt_net:
    :type tenant_mgmt_net: str
    :param tenant_prov_net:
    :type tenant_prov_net: str
    :param tenant_vmot_net:
    :type tenant_vmot_net: str
    """

    _attribute_map = {
        'tenant_mgmt_net': {'key': 'tenantMgmtNet', 'type': 'str'},
        'tenant_prov_net': {'key': 'tenantProvNet', 'type': 'str'},
        'tenant_vmot_net': {'key': 'tenantVmotNet', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(Vpc, self).__init__(**kwargs)
        self.tenant_mgmt_net = kwargs.get('tenant_mgmt_net', None)
        self.tenant_prov_net = kwargs.get('tenant_prov_net', None)
        self.tenant_vmot_net = kwargs.get('tenant_vmot_net', None)
